from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseLevelWindow(object):
    def setupUi(self, ChooseLevelWindow):
        ChooseLevelWindow.setObjectName("ChooseLevelWindow")
        ChooseLevelWindow.resize(512, 370)
        self.centralwidget = QtWidgets.QWidget(ChooseLevelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_level_label = QtWidgets.QLabel(self.centralwidget)
        self.choose_level_label.setGeometry(QtCore.QRect(20, 0, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(22)
        self.choose_level_label.setFont(font)
        self.choose_level_label.setObjectName("choose_level_label")
        self.easy_button = QtWidgets.QPushButton(self.centralwidget)
        self.easy_button.setGeometry(QtCore.QRect(20, 70, 231, 41))
        self.easy_button.setObjectName("easy_button")
        self.medium_button = QtWidgets.QPushButton(self.centralwidget)
        self.medium_button.setGeometry(QtCore.QRect(20, 120, 231, 41))
        self.medium_button.setObjectName("medium_button")
        self.hard_button = QtWidgets.QPushButton(self.centralwidget)
        self.hard_button.setGeometry(QtCore.QRect(20, 170, 231, 41))
        self.hard_button.setObjectName("hard_button")
        self.random_button = QtWidgets.QPushButton(self.centralwidget)
        self.random_button.setGeometry(QtCore.QRect(20, 220, 231, 41))
        self.random_button.setObjectName("random_button")
        self.return_to_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.return_to_menu_button.setGeometry(QtCore.QRect(80, 280, 101, 41))
        self.return_to_menu_button.setObjectName("return_to_menu_button")
        self.levels_description_label = QtWidgets.QLabel(self.centralwidget)
        self.levels_description_label.setGeometry(QtCore.QRect(320, 90, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(16)
        self.levels_description_label.setFont(font)
        self.levels_description_label.setObjectName("levels_description_label")
        self.easy_label = QtWidgets.QLabel(self.centralwidget)
        self.easy_label.setGeometry(QtCore.QRect(320, 130, 31, 16))
        self.easy_label.setObjectName("easy_label")
        self.medium_description_label = QtWidgets.QLabel(self.centralwidget)
        self.medium_description_label.setGeometry(QtCore.QRect(360, 150, 141, 16))
        self.medium_description_label.setObjectName("medium_description_label")
        self.hard_description_label = QtWidgets.QLabel(self.centralwidget)
        self.hard_description_label.setGeometry(QtCore.QRect(350, 170, 111, 16))
        self.hard_description_label.setObjectName("hard_description_label")
        self.easy_description_label = QtWidgets.QLabel(self.centralwidget)
        self.easy_description_label.setGeometry(QtCore.QRect(350, 130, 131, 16))
        self.easy_description_label.setObjectName("easy_description_label")
        self.medium_label = QtWidgets.QLabel(self.centralwidget)
        self.medium_label.setGeometry(QtCore.QRect(320, 150, 41, 16))
        self.medium_label.setObjectName("medium_label")
        self.hard_label = QtWidgets.QLabel(self.centralwidget)
        self.hard_label.setGeometry(QtCore.QRect(320, 170, 31, 16))
        self.hard_label.setObjectName("hard_label")
        self.random_description_label = QtWidgets.QLabel(self.centralwidget)
        self.random_description_label.setGeometry(QtCore.QRect(370, 190, 111, 16))
        self.random_description_label.setObjectName("hard_description_label_2")
        self.random_label = QtWidgets.QLabel(self.centralwidget)
        self.random_label.setGeometry(QtCore.QRect(320, 190, 51, 16))
        self.random_label.setObjectName("hard_label_2")
        ChooseLevelWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChooseLevelWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 21))
        self.menubar.setObjectName("menubar")
        ChooseLevelWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChooseLevelWindow)
        self.statusbar.setObjectName("statusbar")
        ChooseLevelWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChooseLevelWindow)
        QtCore.QMetaObject.connectSlotsByName(ChooseLevelWindow)

    def retranslateUi(self, ChooseLevelWindow):
        _translate = QtCore.QCoreApplication.translate
        ChooseLevelWindow.setWindowTitle(_translate("ChooseLevelWindow", "MainWindow"))
        self.choose_level_label.setText(_translate("ChooseLevelWindow", "Choose a game level:"))
        self.easy_button.setText(_translate("ChooseLevelWindow", "EASY"))
        self.easy_button.setStyleSheet('QPushButton {color: green;}')
        self.medium_button.setText(_translate("ChooseLevelWindow", "MEDIUM"))
        self.medium_button.setStyleSheet('QPushButton {color: orange;}')
        self.hard_button.setText(_translate("ChooseLevelWindow", "HARD"))
        self.hard_button.setStyleSheet('QPushButton {color: red;}')
        self.random_button.setText(_translate("ChooseLevelWindow", "RANDOM"))
        self.random_button.setStyleSheet('QPushButton {color: blue;}')
        self.return_to_menu_button.setText(_translate("ChooseLevelWindow", "Return to menu"))
        self.levels_description_label.setText(_translate("ChooseLevelWindow", "Levels description:"))
        self.easy_label.setText(_translate("ChooseLevelWindow", "EASY"))
        self.easy_label.setStyleSheet('color: green;')
        self.medium_description_label.setText(_translate("ChooseLevelWindow", " - words length from 6 to 10 "))
        self.hard_description_label.setText(_translate("ChooseLevelWindow", " - words longer than 10 "))
        self.easy_description_label.setText(_translate("ChooseLevelWindow", "- words length from 2 to 5 "))
        self.medium_label.setText(_translate("ChooseLevelWindow", "MEDIUM"))
        self.medium_label.setStyleSheet('color: orange;')
        self.hard_label.setText(_translate("ChooseLevelWindow", "HARD"))
        self.hard_label.setStyleSheet('color: red;')
        self.random_description_label.setText(_translate("ChooseLevelWindow", "- all avaible words"))
        self.random_label.setText(_translate("ChooseLevelWindow", "RANDOM"))
        self.random_label.setStyleSheet('color: blue;')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChooseLevelWindow = QtWidgets.QMainWindow()
    ui = Ui_ChooseLevelWindow()
    ui.setupUi(ChooseLevelWindow)
    ChooseLevelWindow.show()
    sys.exit(app.exec_())
